### ISSUE TITLE
Where is ultimate_stats.amxx?

### ISSUE THREAD

**Issue by tokp** [TheDoctor0/UltimateStats#2]
Hello, I read the documentation but I didn't find any ultimate_stats.amxx file. Checking old commits I saw a ultimate_stats.amxx file but it not works, it throw this message on a linux server:

> L 05/08/2019 - 11:11:06: [AMXX] Load error 17 (invalid file format or version) (plugin "ultimate_stats.amxx")

**Comment by TheDoctor0** [comment]
After project cleanup compiled version of the plugin can be only found in [ultimate_stats.zip](https://github.com/TheDoctor0/UltimateStats/releases/download/1.0/ultimate_stats.zip) in a release.
You can also compile the plugin locally using compiler included in Base Package of AMXX [dev releases](https://www.amxmodx.org/downloads-new.php).

Of course, as this plugin is only compatible with AmxModX 1.8.3 / 1.9, you cannot use it on older versions or even compile it using older compiler.
