### ISSUE TITLE
Top15

### ISSUE THREAD

**Issue by eryk172** [TheDoctor0/UltimateStats#4]
![image](https://user-images.githubusercontent.com/47436122/58195231-cc557700-7cc7-11e9-974c-7158e45a96aa.png)

Tak to wygląda, graczy który dopiero wbije zdobędzie kilka fragów trzyma się w top15.

Może top15 zrobić standardowe a dodać /topskill ?
p.s jak wpiszesz /ak47top15 to dziala, a z menu juz nie

**Comment by TheDoctor0** [comment]
W przypadku rankingu opartego na elo (skill) właściwie zawsze tak będzie,
więc właściwie miałoby to sens, żeby wydzielić topkę skilla jak w przypadku czasu gry.

Co do wyboru broni z menu statystyk, nie działa tylko AK47?

**Comment by eryk172** [comment]
Z kazda bronia

**Comment by TheDoctor0** [comment]
No to zgaduję, że pewnie jakaś literówka przy formatowaniu stringa z komendą.
Poprawię to przy okazji 😉
