### ISSUE TITLE
get_user_stats doesn't return actual player rank

### ISSUE THREAD

**Issue by rivit98** [TheDoctor0/UltimateStats#5]
get_user_stats always return 1.
According to original CSX/CSSTATS implementation it should return player rank.
This is true for get_user_stats2 too.

Also I think that dedicated native for getting user position (rank) would be nice.

**Comment by TheDoctor0** [comment]
Great catch 👍 
I'll fix it when I will have some time.
Yeah, I think native like _get_user_rank_ would be a good addition.
