### ISSUE TITLE
[Feature Request] Adding new cvar enable / disable stats

### ISSUE THREAD

**Issue by Takanashi-Rikka1** [TheDoctor0/UltimateStats#8]
Hey!
first of all i wanna thank you for such great plugin.

i wonder if it's possible for you, adding new cvar like "ultimate_stats_enable 0/1"
simply to enable / disable the stats, or another suggestion is adding ultimate_stats_counting 0/1
to stop counting.
the reason that there are servers which using it for 5vs5(like me xd), default mode is warmup
so you wanna counting only on live match to show reliable information of players.
while match is running you can insert the new cvar to run with all cvars.

that's all, i don't know if the project is still active, it's been a long time.
thank you anyway

**Comment by TheDoctor0** [comment]
Hi @Takanashi-Rikka1.

The project is not active at this point but adding a cvar for that is quite easy to accomplish.

You can follow guides like https://forums.alliedmods.net/showthread.php?t=85316 or https://forums.alliedmods.net/showthread.php?t=154642. Or you can ask on that forum to add such a cvar, I'm sure someone will be eager to help.
