### ISSUE TITLE
No English support?

### ISSUE THREAD

**Issue by SamuelGogarty** [TheDoctor0/UltimateStats#9]
![image](https://github.com/user-attachments/assets/d3150ccf-02ae-45d6-8db5-57b4e55edbc0)

I cannot find any translation file included nor any option in the config to switch the language to english

**Comment by TheDoctor0** [comment]
Hey @SamuelGogarty.
This plugin was written by me for use only on Polish servers, so if you want to have an English version,
you will need to translate it - ChatGPT or even https://www.deepl.com/en/translator should help here.
